package com.pojo;

// Generated Aug 11, 2020 12:50:14 PM by Hibernate Tools 3.4.0.CR1

/**
 * Demo generated by hbm2java
 */
public class Demo implements java.io.Serializable {

	private Integer id;
	private String name;
	private String img;

	public Demo() {
	}

	public Demo(String name, String img) {
		this.name = name;
		this.img = img;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

}
